# Generated by Django 5.0.3 on 2024-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('RR', 'Double Rare'), ('RRR', 'Triple Rare'), ('SR', 'Super Rare'), ('SIR', 'Special Art'), ('HR', 'Hyper Rare'), ('UR', 'Ultra Rare'), ('SSR', 'Shiny Super Rare'), ('S', 'Shiny'), ('CHR', 'Character Rare'), ('CSR', 'Character Super Rare'), ('A', 'Amazing Rare'), ('K', 'Radiant Rare')], default='C', max_length=25)),
                ('set', models.CharField(max_length=100)),
                ('price_ungraded', models.IntegerField()),
                ('price_psa10', models.IntegerField()),
            ],
        ),
    ]
