# Generated by Django 5.0.3 on 2024-03-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_card_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'C'), ('uncommon', 'U'), ('rare', 'R'), ('double_rare', 'RR'), ('triple_rare', 'RRR'), ('super_rare', 'SR'), ('special_art', 'SIR'), ('hyper_rare', 'HR'), ('ultra_rare', 'UR'), ('shiny_super_rare', 'SSR'), ('shiny', 'S'), ('character_rare', 'CHR'), ('character_super_rare', 'CSR'), ('amazing_rare', 'A'), ('radiant_rare', 'K')], default='common', max_length=25),
        ),
        migrations.CreateModel(
            name='PriceUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_ungraded', models.IntegerField(max_length=1000000)),
                ('price_psa10', models.IntegerField(max_length=1000000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
            ],
        ),
    ]
