# Generated by Django 5.0.3 on 2024-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_priceupdates_priceupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceupdate',
            old_name='price_psa10',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='priceupdate',
            name='price_ungraded',
        ),
        migrations.AddField(
            model_name='priceupdate',
            name='grade',
            field=models.CharField(choices=[('UG', 'Ungraded'), ('01', 'PSA 1'), ('02', 'PSA 2'), ('03', 'PSA 3'), ('04', 'PSA 4'), ('05', 'PSA 5'), ('06', 'PSA 6'), ('07', 'PSA 7'), ('08', 'PSA 8'), ('09', 'PSA 9'), ('10', 'PSA 10')], default='UG', max_length=2),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='date',
            field=models.DateField(verbose_name='Priced Date'),
        ),
    ]
