# Generated by Django 5.0.3 on 2024-03-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_collection_card_collections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Deck',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='collections',
            new_name='decks',
        ),
    ]
