# Generated by Django 5.0.3 on 2024-03-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_collection_deck_rename_collections_card_decks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price_psa10',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_ungraded',
        ),
    ]
