# Generated by Django 5.0.3 on 2024-03-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='card',
        ),
    ]
