# Generated by Django 5.0.3 on 2024-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_cat_photo_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('Common', 'C'), ('Uncommon', 'U'), ('Rare', 'R'), ('Double Rare', 'RR'), ('Triple Rare', 'RRR'), ('Super Rare', 'SR'), ('Special Art', 'SIR'), ('Hyper Rare', 'HR'), ('Ultra Rare', 'UR'), ('Shiny Super Rare', 'SSR'), ('Shiny', 'S'), ('Character Rare', 'CHR'), ('Character Super Rare', 'CSR'), ('Amazing Rare', 'A'), ('Radiant Rare', 'K')], default='Common', max_length=25),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='grade',
            field=models.CharField(choices=[('UG', 'Ungraded'), ('1', 'PSA 1'), ('2', 'PSA 2'), ('3', 'PSA 3'), ('4', 'PSA 4'), ('5', 'PSA 5'), ('6', 'PSA 6'), ('7', 'PSA 7'), ('8', 'PSA 8'), ('9', 'PSA 9'), ('10', 'PSA 10')], default='UG', max_length=2),
        ),
    ]
